import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "./components/MainLayout";

export const metadata: Metadata = {
  title: {
    default: "Persian Book",
    template: "Persian Book | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html dir="rtl" lang="fa">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
